### ISSUE TITLE
clicking next page does not auto scroll up on the deaths page

### ISSUE THREAD

**Issue by RSG250** [goonstation/api#1]
clicking the arrow for next page on the deaths section, of the events section,  does NOT force your page to scroll to top. on the goon hub website 

addtional info:
had it set to show 50 records per page

**Comment by Wirewraith** [comment]
Forgot to tag the issue in the commit, resolved with https://github.com/goonstation/api/commit/c240dfc47c0647cb2bc970ca98de85f586af3682
