### ISSUE TITLE
Detecting of round end is wonky.

### ISSUE THREAD

**Issue by mordent-goonstation** [goonstation/api#16]
https://goonhub.com/admin/logs?sort_by=ended_at

![image](https://github.com/goonstation/api/assets/62817778/2dd61d4d-e4c5-4585-bd25-d99ad15e9011)

Currently an entire page (and one extra row) of "Round in progress" rounds.

Examining one of those rounds shows "In Progress" in the top right, even though it isn't.

I would expect to see only rounds that are actually in progress show as in progress. I would imagine this is to do with how round end is determined, and possibly coincides with hard restarts.

**Comment by Wirewraith** [comment]
Fixed with https://github.com/goonstation/api/commit/05924f5d50beb184d26b4800729b55e1db33e45b
