### ISSUE TITLE
The player notes list route is fuzzy searching and displaying other people's notes (!!!)

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/api#24]
The player notes route used by the discord notes command is fuzzy searching, meaning asking it for `Someone`'s notes will display notes from `SomeoneElse` and `NotSomeone`.

This is very bad for obvious reasons.

**Comment by Wirewraith** [comment]
Usage issue from request built ingame, fixed via https://github.com/goonstation/goonstation/commit/cb2463604cdafb565bd590852a7726da65091b6d
